### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by ElementJason** [xaniox/simple-trading#5]
I recently installed the plugin on a server running spigot 1.9.4 
i gave my staff member the permissions simpletrade.trade but yet it still says he has no permission to trade

**Comment by ArtificialTruth** [comment]
Have you tried stopping the server, giving him the permission, and starting it again?

**Comment by xaniox** [comment]
Seems like I messed the permissions on the Spigot page up. They are actually simpletrading.trade, simpletrading.reload and simpletrading.sign.

I'll change the permissions to the correct ones.
