### ISSUE TITLE
Add a option to have shift-click trading

### ISSUE THREAD

**Issue by starwarsfreak219** [xaniox/simple-trading#8]
I was wondering if you can add an option where you would be able to decide whether you want Shift-Click Trading or not... the Shift-Click overrides some Shift-Clicking plugins for players and I think adding a Boolean to allow it to be used or not would be great. Hope you can add it! ☺

**Comment by xaniox** [comment]
Implemented in the latest development build #28
https://ci.xaniox.de/job/SimpleTrading/
